const express= require('express')
const { registerUser,login }=require('../controllers/userController')
const {authentication, authorisation}=require('../authentication/authentication')
const {addReview,updateReview,deleteReview}=require('../controllers/reviewController')
const {createBook, getAllBooks,getBook, updateBook, deleteBook}=require('../controllers/bookController')
const router= express.Router()
router.post('/register',registerUser )
router.post('/login',login)
router.post('/books',createBook)
router.get('/books',authentication,getAllBooks)
router.get('/books/:bookId',authentication,getBook)
router.put('/books/:bookId',authentication,authorisation,updateBook)
router.delete('/books/:bookId',authentication,authorisation,deleteBook)
router.post('/books/:bookId/review',addReview)
router.put('/books/:bookId/review/:reviewId',updateReview)
router.delete('/books/:bookId/review/:reviewId',deleteReview)
module.exports=router